Repository woorifisa-service-dev-4th/frontend-1st-woori-account-book, pull requests merged in 2025-01, with the labels that each got.

#5 Feat: 메뉴 탭 구현
  index.html
  logo.png
  style.css
Labels: feature

#6 Feat: 가계부 표 구현
  index.html
  style.css
Labels: feature

#10 Refactor: 가계부 입력 및 표 레이아웃 수정
  index.html
  style.css
Labels: Refacotr

#17 Feat: 표 스크롤바 추가
  index.html
  style.css
Labels: feature

#22 feat: gitignore 설정
  .gitignore
  style.css
Labels: feature

#23 Feat: 테이블 정렬 기능 구현
  index.html
  sort.js
  style.css
Labels: feature

#24 Fix: 버튼 효과 분리
  sort.js
  style.css
Labels: fix

#27 Feat: 입력 기능 구현
  .DS_Store
  index.html
  input.js
  style.css
Labels: feature

#28 Feat: input 타입, 글자수 제한, option 선택안되어있을때는 추가불가, 추가한 후 추가창 띄우기
  index.html
  input.js
Labels: feature

#29 Fix: 테이블 입력 규격에 맞게 변경
  index.html
Labels: fix

#32 Fix: 오타 수정
  index.html
  input.js
  modal.js
  style.css
Labels: fix

#34 Feat: 테이블 모달창 기능 구현
  modal.js
  sort.js
Labels: feature

#35 Feat: 그래프 기능 구현
  graph.js
  index.html
  style.css
Labels: feature

#36 Feat: 그래프 hover 기능 구현
  graph.js
  index.html
  style.css
Labels: feature

#38 Fix: git conflict 해결
  .gitignore
  README.md
  eslint.config.mjs
  graph.js
  index.html
  input.js
  logo.png
  modal.js
  package-lock.json
  package.json
  sort.js
  style.css
Labels: bug
